data/airspace.json
We should remove this link because the server of Austro Control prevents direct downloads of this file.
Look here for more details:
http://bugs.xcsoar.org/ticket/3500
=> Removed Austrian airspace

test.js
request was not able to parse the HEAD response of soaringweb due to unknown
reasons. The statusCode however was always present on the request object and
since that is all we need we can just use it like before.
Resolves #40
=> test: Work around request parsing failure

data/airspace.json
Updates in airspace from version 16_3 to 16_3a:
- Changed Schiphol TMA 1 to exclude Lelystad ATZ B
- Minor format changes
=> Update Netherlands airspace in airspace.json

data/airspace.json
I tried to solve the broken Australian airspace but it appears that there's an issue with soaringweb in that all the Australian airspace files on the website return 404's.
I've emailed the website maintainer to make him aware.
=> Updated Polish airspace

data/airspace.json
Got a response from the soaringweb.org maintainer and he's fixed the links on the website to the updated airspace files.
All tests should now be passing.
=> Updated Australia airspace

.travis.yml
This fixes the build error (`const os = require('os'); [...] SyntaxError: Use of const in strict mode.`) caused by a highly outdated nodejs-version (`v0.10.48`) (see also https://stackoverflow.com/a/23151062/1741342).
Updating to an even newer nodejs-version than `v4.x` should be considered but I've no clue about what is appropriate.
@Turbo87 Can you give an advice which nodejs-version whe should target and how to update the dependencies to meet this version?
=> CI: Use NodeJS v4.x in the default travis dev env

data/waypoints-special.json
New Waypoints version. The questions is whether we should rename the destination file to 2018a?
=> New Waypoints 2018a for BGA

data/flarmnet.json
Flarmnet will be gone a few days or weeks as they are reconstructing. In the meantime we should provide the ogn database.
=> Switching to device database for OGN, as flarmnet is not available

data/waypoints-special.json
depends on https://github.com/XCSoar/xcsoar-data-content/pull/79
=> url now hosted at download.xcsoar.org new waypoint-special mechanism

data/airspace.json
New Filepath for Northen NewZealand
Split North/South Island. Same ISO code might prove a challenge in the future.
=> split newzealand into north/south new airspace for south island.

data/airspace.json
Removed the date from the UK airspace file name to avoid having to update the repository with every airspace update. The airspace file includes date information in the header.
=> Rename UK airspace file

data/airspace.json
Removed the outdated airspace uris for austria and added the current airspace file from austrocontrol eaip.
[Source](https://www.austrocontrol.at/piloten/vor_dem_flug/aim_produkte/luftraumstruktur)
=> Airspace austria

data/airspace.json
This one is a bit weird, because the changes are said to be starting at 2020-05-21, but today it is 2020-05-14. However, the old airspace file (sverige-2020-cu-rev1.txt) is no longer available, so it's better that we submit this new one (sverige-2020-cu-rev2.txt) instead.
=> Update Sweden airspace

data/airspace.json
Following issue #151, the French airspace file was updated on the http://soaring.gahsys.com website.
This PR updates the information about the French airspace.
Note sure about the update date: I set it to 2020-04-23 because the header of the file states the information source is "AIP FRANCE 2020/04/23". However, the file was uploaded on the French Gliding Federation on 2020-05-05. 
So, if this PR is fine, this closes #151.
=> French airspace: update link to file

data/airspace.json
Changed from gahsys.com to segelflyget.se as source because the former had screwed up encoding of the file.
=> Update Sweden airspace to 2020-rev7

data/airspace.json
FFVP updated the airspace for France, and the file is now on soaring.gahsys.com. So, updating...
=> Update of French airspace

data/airspace.json
Updating Canadian Airspace, effective December 31, 2020.  File has been updated in xcsoar-data-content
=> Update Canadian Airspace for Dec 31, 2020

data/airspace.json
Please note: The date in the file and the version inside the file implies that this airspace is from 2020, but I couldn't find any information clearly saying from which date this airspace information is valid. For that reason I entered the only date I could find, which is "Dated 21 January 2021" as mentioned inside the file.
=> Update Hungary airspace to 2020v7

data/airspace.json
Updated the austrian airspace link.
Source: e-aip austrocontrol
https://www.austrocontrol.at/piloten/vor_dem_flug/aim_produkte/luftraumstruktur
=> updated Austrian Airspace valid from 2020-12-03

data/airspace.json
The mirror of gahsys seems to be down, and isn't coming back up even after 24h outage.
=> replacing soaring.gahsys with silentflight mirror

data/airspace.json
1) Use soaringweb.org instead of soaring.guenther-eichhorn.com, as this is the domain that is used in the links for airspaces on their website.
2) Use https instead of http, as the website redirects to this.
Closes #191.
=> Update to canonical URLs for soaringweb.org

data/airspace.json
Hi,
Both "WEEK" and "WEEKEND" links for Belgium-Luxembourg in `airspace.json` have been pointing to the "WEEK" airspace file, which is incorrect. The "WEEKEND" URI is now switched to use the actual "WEEKEND" file.
In addition I'm updating "WEEK" link to use the latest "WEEK" airspace file available from SoaringWeb. The one that's currently referenced by XCSoar repo has some syntax issue, resulting in a "parse error", while the latest one is read correctly.
Please let me know if I have to do some additional verification for this to be merged.
=> Fix Belgium-Lux weekend airspace URI & update week airspace URI

data/maps.json
NB: Dependent on https://github.com/XCSoar/xcsoar-data-maps/pull/5 being merged, and the ZA map generating successfully.
Motivation:
* The AFR_GARIEP_DAM map is already ~93% of the land area of South Africa (so rather use the new, entire ZA map), yet does not contain the very popular Cape Gliding Club mountain ridges.
* Gariep Dam is better described as being in the country of South Africa (ZA), as opposed to the continent of Africa.
=> Add South Africa in its entirety, and removed AFR_GARIEP_DAM subsection.

data/airspace-special.json
This airspace adds Recommended/Restricted/Prohibited LZs and dangers/obstacles (like power lines), for the most active flying sites for hang gliders and paragliders in Australia.
The airspace file is managed by several clubs members and it is continuously updated, due the continuous changes and agreements with the land owners.
Source: https://siteguide.org.au/
=> Airspace: add Australia HG/PG SiteGuide

data/airspace.json
The current URL returns 404 and is outdated regardless.
Source: https://soaringweb.org/Airspace/AU.html#AU (All Classes, OpenAir format)
=> Update Australia airspace

test.js
Added 2 extra checks in the _test_ script:
1) Check for a valid Unix/Windows filename ([source](https://stackoverflow.com/a/11101624))
2) Check is the extension matches the type (skips if _type_ is not set)
**NB**: it requires #220 to be merged first in order to pass the test.
Example of output:
=> Test: check for valid filename and extension

data/airspace-special.json
So it shows up in the airspace list dialog when downloaded see: #220
=> cz/pl wave airspace: change filename extension
