check_repo_urls.sh
Added template arguments to mktemp, as osx requires them.
=> Check URls for availability, now osx compatible.

.gitignore, .travis.yml, package.json, test.js
... including TravisCI support (see https://travis-ci.org/Turbo87/xcsoar-data-repository/builds/48266885)
=> Use MochaJS as URL checker

repository
source: https://www.gliderpilotshop.com/databases
/cc @roeles
=> Update Dutch airspace file

repository
Add an entry for the airspace in Bulgaria. I have not tested this from within XCSoar because editing my installation's repository file has no effect and it gets overwritten. The airspace file is updated daily.
=> Add Bulgaria airspace

repository
source: http://www.daec.de/fachbereiche/luftraum-flugbetrieb/luftraumdaten/
=> Update German airspace file

data/airspace.json
From official source (FFVV): http://www.ffvvespaceaerien.org/?page_id=412
see http://www.volavoile.net/index.php?showtopic=10082&page=2#entry100981
=> Permalink for France airspace

data/airspace.json
=> New swiss aIrspace fille

data/airspace.json
New Format Airspace for the UK
=> New UK Airspace

data/airspace.json
http://www.daec.de/fachbereiche/luftraum-flugbetrieb/luftraumdaten/
=> Update german airspace

data/airspace.json
=> Updated French airspace links

data/airspace.json
Updated The Netherlands airspace. File obtained through this website:
https://www.gliderpilotshop.com/databases
=> Update The Netherlands airspace

.travis.yml
Resolves https://github.com/XCSoar/xcsoar-data-repository/issues/54#issuecomment-241202038
=> CI: Fix broken "before_install" and "after_success" blocks

data/airspace.json
=> Update US airspace

data/airspace.json, data/airspace/nl.txt
Please try to verify if my guess of what the URL will be is right. If not, let me know.
=> Include Netherlands airspace 2017 in the repo, and update URL

data/waypoints-special.json
=> waypoints: Fix BGA2017.dat file extension

README.md
=> README: Update instructions

data/airspace.json
Corrected the file path. Soaringweb got it wrong.
=> update france airspace

data/waypoints-by-country.json
=> Fix `Germany.cup` URL

data/flarmnet.json
See https://github.com/XCSoar/XCSoar/pull/106 for more info.
=> add link to ogn device database (FLARM compatible)

data/airspace.json
The airspace has been updated.
=> Updated airspace for Australia

data/airspace.json
=> Update candian airspace

data/airspace.json, data/waypoints-by-country.json
This pr depends upon this pr: https://github.com/XCSoar/xcsoar-data-content/pull/20
=> new uk airspace and waypoint file 2019-02-28

data/airspace.json
Removal of an uncompleted merge.
=> git merge correction

data/EH1904.txt, data/airspace.json
I'll leave my repository online for the next year, so the raw-URL will keep working.
The original file can be obtained through www.gliderpilotshop.nl, but it links towards a dropbox location. I have permission to copy the file for the purpose of sharing it with XCSoar users.
=> Dutch airspace 2019

data/airspace.json
Change location to http://download.xcsoar.org/airspaces for easier updating
=> Change Czech airspace location

data/airspace.json
Depends on https://github.com/XCSoar/xcsoar-data-content/pull/66 includes fix in airspace.json
=> airspace for switzerland at new location

data/airspace.json
point to http://download.xcsoar.org/airspaces/Slovakia_Airspace.txt
=> Change Slovakia Airspace download location

data/airspace.json
=> Fixfranceandusa

data/airspace.json
This should be merged together with this pull request:
https://github.com/XCSoar/xcsoar-data-content/pull/76
=> Update Dutch airspace to version EH1904A

data/airspace.json
Has been fixed by john laibacher.
=> US Airspace 

data/airspace.json
=> german airspace 20191216

data/waypoints-special.json
related data content: #https://github.com/XCSoar/xcsoar-data-content/pull/100
=> data/waypoints-special.json: waypoints for 2nd Spreewaldpokal in Bronkow

data/airspace.json
Metadata update to align with: https://github.com/XCSoar/xcsoar-data-content/pull/102
=> update metadata for cechz_airspace

data/airspace.json
Please merge after https://github.com/XCSoar/xcsoar-data-content/pull/104
=> Change Netherlands airspace to 2020

data/airspace.json
This resource is no longer available on http, only on https.
=> sweden airspace 2020

data/airspace.json
source: https://www.daec.de/fachbereiche/luftraum-flugbetrieb/luftraumdaten/
=> airspace: new airspace for germany from 2020-03-26

data/airspace.json
New Austrian-Airspace file in the eAIP of AustroControl
Source: [ACG](https://www.austrocontrol.at/piloten/vor_dem_flug/aim_produkte/luftraumstruktur)
=> airspace: austria valid from 21.05.2020

data/airspace.json
Altering the link to the French airspace file to account for its monthly update.
Note: I supposed that opening an issue was not necessary. Please, correct me if I am wrong.
=> French airspace: monthly update

data/airspace.json
Please merge together with https://github.com/XCSoar/xcsoar-data-content/pull/114
=> Update Netherlands airspace to version 18-jun-2020

data/airspace.json
New month -> new airpsace file :-)
AustroControl offers a new airspace file for austria on eAIP.
[Source](https://www.austrocontrol.at/piloten/vor_dem_flug/aim_produkte/luftraumstruktur)
[Airspace-File](https://www.austrocontrol.at/jart/prj3/ac/data/dokumente/austria_acg_airspaces_2020-06-18_xcsoar_2020-05-05_1105482.txt)
=> airspace.json: updated austria

data/airspace.json
Updated Canadian airspace file
=> Update Canadian Airspace

data/waypoints-special.json
Added Proving Grounds Tasks for Canada.  Proving Grounds: https://soaringtasks.com/
=> Add Proving Grounds Waypoints and Tasks

data/airspace.json
Add the US border for use in Canada.
=> Add CAN_USborder.txt

data/airspace.json
Added from http://download.xcsoar.org/airspaces/Canada_Airspace.txt effective Nov 5, 2020
https://soaringtasks.com/canairspace/
=> Update Canadian Airspace Link

data/airspace.json
Version 21.02-25.2 effective 2021-02-25. Source: http://soaring.gahsys.com/Airspace/NA/
=> Update USA airspace

data/airspace.json
to actually expose 
https://github.com/XCSoar/xcsoar-data-content/pull/144
=> update swiss airspace

data/airspace.json
=> Update airspace.json Canadian Airspace Date
